### ISSUE TITLE
`keep.getNotes()` endpoint?

### ISSUE THREAD

**Issue by christiangenco** [kiwiz/gkeepapi#1]
What needs to happen to get Google Keep notes? I'd be happy to help if pointed in the right direction!

**Comment by kiwiz** [comment]
Do you mean getting all the notes? You can achieve this by calling
`keep.all()`.

**Comment by kiwiz** [comment]
Oh, the docs button on the README links to the documentation. I can add
another link to make it more apparent.

**Comment by kiwiz** [comment]
@christiangenco is your issue resolved?

**Comment by christiangenco** [comment]
Oh perfect - I must've missed the link to the documentation.

This is awesome :D 🕺
