### ISSUE TITLE
Shouldn't createList() respect items order, or at least accept an additional parameter to that effect?

### ISSUE THREAD

**Issue by stepnem** [kiwiz/gkeepapi#101]
Minimal illustration:

```python
def test_createList_order():
    keep = gkeepapi.Keep()
    sample = [
        keep.createList("Title", [("Item 1", True), ("Item 2", False)])
        .items[0]
        .checked
        for _ in range(1000)
    ]
    print(
        f"Item 1 ended up first {sample.count(True)} times,\n"
        f"Item 2 ended up first {sample.count(False)} times."
    )
```

It seems to me that for creating a list of ordered items, one currently has to use `createList()` without the `items` parameter to make an empty list, and consequently add each item using `List.add()`, supplying the `sort` parameter. Is there any reason not to respect the order in the `items` parameter? And if there is, could `createList()` please be modified to accept another parameter?

**Comment by kiwiz** [comment]
Nope, just an oversight. The order is random by default, so I think it's reasonable to update the default behaviour here. `0.13.3` should do the trick.

**Comment by stepnem** [comment]
> 0.13.3 should do the trick.

It does. Thank you!
