### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by Avangunite** [kiwiz/gkeepapi#102]
I am following gkeepapi's docs and did this:
```
keep = gk.Keep()
keep.login(USERNAME, PASSWORD)
```
but however I get this error:
```
gkeepapi.exception.LoginException: ('BadAuthentication', None)
```
Both the USERNAME and PASSWORD are valid. Do I need to change something in my account to allow access? The docs don't mention anything about that.

Thanks in advance.

**Comment by davidpcaldwell** [comment]
See discussion in #81.
