### ISSUE TITLE
Add something to list, not note.

### ISSUE THREAD

**Issue by SsNipeR1** [kiwiz/gkeepapi#104]
Please make sure you've done the following before submitting your issue:

- [ installed using pip3 install gkeepapi] Check that you're running the newest version of the library.
- [ i'll not provide stack trace and idk whats that :)] If you're providing a stack trace, make sure it doesn't contain your password.
- [ ] If you're getting a KeyError or ParseException, please follow the instructions [here](https://gkeepapi.readthedocs.io/en/latest/#reporting-errors) to dump the raw data.

Additionally, please provide the following information:

- [ ubuntu 20.04] Operating system
- [ 3.8.5] Python version
How to **add** something to list? I have shopping list and i dont know how to **add** something to list, not note. I didnt found something in documentation.

**Comment by hmccarty** [comment]
Taken from the documentation:

```python
# Create a checked item
glist.add('Item 2', True)

# Create an item at the top of the list
glist.add('Item 1', True, gkeepapi.node.NewListItemPlacementValue.Top)

# Create an item at the bottom of the list
glist.add('Item 3', True, gkeepapi.node.NewListItemPlacementValue.Bottom)
```

**Comment by hmccarty** [comment]
@kiwiz Can we close this issue?

**Comment by kiwiz** [comment]
Oh yup, thanks for addressing it.
