### ISSUE TITLE
gpsoauth issue

### ISSUE THREAD

**Issue by kirkmaba77** [kiwiz/gkeepapi#105]
(fyi, I'm new to python...)

I used gkeepapi on windows and it work great.
I moved to a linux system today and had issues, seems the default/latest gpsoauth (0.4.3) which was installed with gkeepapi  has issues. 
I changed to use a previous gpsoauth (pip install  gpsoauth==0.4.2)  and that now works.

Thx,
B

Please make sure you've done the following before submitting your issue:

- [ ] Check that you're running the newest version of the library.
gkeepapi 0.13.4
(as found on https://pypi.org/project/gkeepapi/)

- [ ] If you're providing a stack trace, make sure it doesn't contain your password.
Traceback (most recent call last):
  File "gkeep-add-to-seattle.py", line 13, in <module>
    success = keep.login('***USER', '***PASSWORD')
  File "/usr/local/lib/python3.7/site-packages/gkeepapi/__init__.py", line 695, in login
    ret = auth.login(username, password, device_id)
  File "/usr/local/lib/python3.7/site-packages/gkeepapi/__init__.py", line 55, in login
    self._email, password, self._device_id
  File "/usr/local/lib/python3.7/site-packages/gpsoauth/__init__.py", line 104, in perform_master_login
    return _perform_auth_request(data, proxy)
  File "/usr/local/lib/python3.7/site-packages/gpsoauth/__init__.py", line 55, in _perform_auth_request
    session.mount(auth_url, AuthHTTPAdapter())
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 129, in __init__
    self.init_poolmanager(pool_connections, pool_maxsize, block=pool_block)
  File "/usr/local/lib/python3.7/site-packages/gpsoauth/__init__.py", line 49, in init_poolmanager
    context.post_handshake_auth = True
AttributeError: attribute 'post_handshake_auth' of '_ssl._SSLContext' objects is not writable

Additionally, please provide the following information:

- [ ] Operating system
    Virtualization: xen
  Operating System: Amazon Linux 2
       CPE OS Name: cpe:2.3:o:amazon:amazon_linux:2
            Kernel: Linux 4.14.214-160.339.amzn2.x86_64
      Architecture: x86-64

- [ ] Python version
3.7 (but 3.8 seemed to have the same issue,2.x was giving me a different issue)

**Comment by wilhelmklopp** [comment]
just ran into this error on MacOS Big Sur 11.2.1 (20D74)

This probably won't be too useful for you but running `brew update` and then using python 3.9.1 helped me move past this error 😅

**Comment by Trysupe** [comment]
> I moved to a linux system today and had issues, seems the default/latest gpsoauth (0.4.3) which was installed with gkeepapi  has issues. 
> I changed to use a previous gpsoauth (pip install  gpsoauth==0.4.2)  and that now works.

> AttributeError: attribute 'post_handshake_auth' of '_ssl._SSLContext' objects is not writable
 
I had the exact same error with another project which also used gpsoauth. Version 0.4.3 does seem to have _a_ problem. Using v. 0.4.2 also helped me

**Comment by kiwiz** [comment]
Closing in favor of #81
