### ISSUE TITLE
Searching for Notes with find() method returns generator object

### ISSUE THREAD

**Issue by kyrlon** [kiwiz/gkeepapi#107]
Adapted from the [Searching for Notes section](https://gkeepapi.readthedocs.io/en/latest/#searching-for-notes), when attempting to running a search, my return object is a generator object:
```
ex = self.keep.find(query="Groceries")
print(ex)
<generator object Keep.find.<locals>.<genexpr> at 0x0000025B7864EE40>
```
My assumption that it would be a return list object as stated from the source code here at this [line](https://github.com/kiwiz/gkeepapi/blob/master/gkeepapi/__init__.py#L820).

when running the function `keep.all()` I have no problem returning a list object.

Is there something I may have overlooked?

==============================================================================

**_Check that you're running the newest version of the library._**
```
 py -m pip freeze | grep gkeep
gkeepapi==0.13.4
```
**_If you're providing a stack trace, make sure it doesn't contain your password._**
No it does not.

 **_If you're getting a KeyError or ParseException, please follow the instructions [here](https://gkeepapi.readthedocs.io/en/latest/#reporting-errors) to dump the raw data._**

I am not getting a KeyError or ParseException.

**_Operating system_**
```
import platform
platform.platform()
'Windows-10-10.0.19041-SP0'
```
**_Python version_**
```
py --version
Python 3.8.9
```

**Comment by kyrlon** [comment]
A quick hotfix is to simply call list on the generator.

```
list(ex)
print(ex)
[<gkeepapi.node.List ...51EFF9910>]
```

**Comment by kiwiz** [comment]
Thanks for the notice! I've updated the docstring in question to say `Generator` instead (I'm not sure if that's the correct syntax, but it's what Python 3's `typing` module exposes, at least).
