### ISSUE TITLE
Nothing happening

### ISSUE THREAD

**Issue by Drarig29** [kiwiz/gkeepapi#109]
- Operating system: Linux (manjaro)
- Python version: 3.9.5

I was trying the https://github.com/Nekmo/gkeep CLI and it wasn't working (nothing was happening) so I tried to use directly your library with a Python script to find the source of the problem.

And I have no error too.

```py
import gkeepapi
gkeepapi.node.DEBUG = True

keep = gkeepapi.Keep()
success = keep.login('myemail', 'mypassword')
print(success)

notes = keep.all()
print(notes)
```

Here's the output:

```bash
$ python gkeep.py
True
[]
```

I tried with other functions and it's the same.

I precise I don't have 2FA enabled on my account. Also, even the DEBUG mode doesn't print anything.

**Comment by Drarig29** [comment]
LOL, sorry it's not the good Google account. I don't have any Keep notes in this one. Sorry for the notification.

**Comment by kiwiz** [comment]
Glad you figured it out. :star:
