### ISSUE TITLE
How to retrieve all the labels from GKeep

### ISSUE THREAD

**Issue by MagTun** [kiwiz/gkeepapi#111]
I would like to retrieve the names of all the labels in my Gkeep.

I am using `labels = keep.labels()` but then I am unable to extract the name from it. 

I tried   `labels.keys()`,  `labels.values()`,  `labels.get()`,  `labels.getattribute()` but each time I get `'dict_values' object has no attribute ... `. 
From the [doc ](https://gkeepapi.readthedocs.io/en/latest/gkeepapi.html#gkeepapi.Keep.labels), I see that `labels` return `List[gkeepapi.node.Label]` but if I do `labels[0]` I get  `'dict_values' object is not subscriptable`

My Gkeep has labels and if I print `labels` I get `dict_values([<gkeepapi.node.Label object at 0x0000016149827AC0>, <gkeepapi.node.Label object at 0x0000016149834F40>])`

Thanks a lot for your help!

Additionally, please provide the following information:

-  Operating system: Windows 10
- Python version : 3.9.5

**Comment by bew** [comment]
try to do `list(labels)` to get a list instead of an iterator!

To get all the label names, you could do:
```py
label_names = [label.name for label in keep.labels]
```
Or without using that 'scary' one-line syntax, the manual way is:
```py
label_names = []
for label in keep.labels:
  label_names.append(label.name)
```

**Comment by MagTun** [comment]
Thanks so much for this detailed answer @bew! Thanks to you I was able to set up my script to manage my GKeep routine. Thanks!
