### ISSUE TITLE
Cannot dedent list item

### ISSUE THREAD

**Issue by stevearc** [kiwiz/gkeepapi#112]
Running gkeepapi 0.13.4 on Linux with Python 3.8.10

I have been unable to get dedenting a list item to work. I made a minimal repro:
```python
import logging
import sys

import gkeepapi
import keyring

logger = logging.getLogger("test")


def main():
    logging.basicConfig(stream=sys.stdout, level=logging.DEBUG)
    keep = gkeepapi.Keep()
    email = sys.argv[1]
    if len(sys.argv) > 2:
        password = sys.argv[2]
        keep.login(email, password)
    else:
        token = keyring.get_password("google-keep-token", email)
        keep.resume(email, token)
    logger.debug("Creating list")
    note = keep.createList("New list")
    top_item = note.add("top item")
    sub_item = note.add("sub item")
    top_item.indent(sub_item)
    logger.debug(
        "Created %s > %s > %s (%s)",
        note.id,
        top_item.id,
        sub_item.id,
        sub_item.super_list_item_id,
    )
    keep.sync()
    # Now we have a list with one top-level item and one sub-item
    top_item.dedent(sub_item)
    logger.debug("New super_list_item_id: %s", sub_item.super_list_item_id)
    keep.sync()
    # This should be None but it is the same as before
    logger.debug("super_list_item_id after sync: %s", sub_item.super_list_item_id)
    # We *still* have a list with one top-level item and one sub-item :(


if __name__ == "__main__":
    main()
```

Running this script with my account email creates a list with a single root item and one indented item. The dedent call and subsequent sync does not appear to have any effect. From debugging the internals, it seems like everything inside of gkeepapi is as I would expect (the `super_list_item_id` is correctly set to None and sent to the API endpoint). I have attached the log output. Am I doing anything wrong here? Is it possible the API has changed?

[dump.log](https://github.com/kiwiz/gkeepapi/files/6845614/dump.log)

**Comment by kiwiz** [comment]
Thanks for the bug report. Looks like the signal for an unindented ListItem changed to an empty string. I uploaded 0.13.5, which should fix this issue.

**Comment by stevearc** [comment]
Works great! Thanks for the quick fix!
