### ISSUE TITLE
Sync single item

### ISSUE THREAD

**Issue by cculpepper** [kiwiz/gkeepapi#115]
Hello, 

I have a lot of notes, so sync() is pretty slow (1-2 minutes). Is there a way to sync a single item? My use case is a script which prints the contents of a note and returns. Unless I run sync() explicitly, gkeepapi doesn't pull down the latest contents. I wasn't able to find anything specific in the documentation, but I might have missed it

Thank you!

**Comment by kiwiz** [comment]
Unfortunately, there is no way to do so - this is exactly how the official clients work too. You can, however, download just the updates to the node tree if you cache it locally. See [here](https://gkeepapi.readthedocs.io/en/latest/#caching-notes) for details.

Also, if you just need to dump out the contents of a note, you might be able to use https://github.com/kiwiz/keep-cli

**Comment by cculpepper** [comment]
I am caching currently, but it still requires a full sync t o update just one changed note. I'll just delete all my old notes. Thank you!
