### ISSUE TITLE
Is `serverId` a primary key of a note?

### ISSUE THREAD

**Issue by 4l1fe** [kiwiz/gkeepapi#116]
Hey. I'm coding some logic and saving data into a local database and want to reuse any unique identifier. For this purpose, the attribute `serverId` seems what i need. But i'm not sure if it's a primary key of a file/note/data record on the Keep server side.

Do you have any thoughts on it?

**Comment by kiwiz** [comment]
`serverId` should be authoritative, so you can use it as a PKID.

**Comment by 4l1fe** [comment]
Maybe i'm wrong but i have a doubt a note keeps its `serverId` unchangeable. I made an experiment of comparing with [DeepDiff](https://zepworks.com/deepdiff/current/diff.html) two states old and current, which the `Keep` class in after synching, ones. And the DeepDiff's difference showed that some notes `serverId` is changed. 

I don't know how to check such a case to discard the doubt.

Have you had a similar observation?

**Comment by 4l1fe** [comment]
> Maybe i'm wrong but i have a doubt a note keeps its `serverId` unchangeable. I made an experiment of comparing with [DeepDiff](https://zepworks.com/deepdiff/current/diff.html) two states old and current, which the `Keep` class in after synching, ones. And the DeepDiff's difference showed that some notes `serverId` is changed.
> 
> I don't know how to check such a case to discard the doubt.
> 
> Have you had a similar observation?

Seems the assumption that `serverId` value is dynamic is wrong as i didn't order the states elements during comparing and got an incorrect result.
