### ISSUE TITLE
Add type hints

### ISSUE THREAD

**Issue by PrOF-kk** [kiwiz/gkeepapi#118]
Consider adding type hints so type checkers like mypy and on-the-fly documentation can work properly, at least for the most commonly used methods.
The return types are often already included in the documentation but aren't recognised correctly:
![Imgur](https://imgur.com/SRYfTwX.png)
I'd expect something like `(method) get: (note_id) -> gkeepapi.node.TopLevelNode | None` instead

**Comment by kiwiz** [comment]
This was primarily to maintain Py2 compatibility, but we should now be in the clear. All deprecation work is currently tracked in the https://github.com/kiwiz/gkeepapi/tree/deprecate_py2 branch. If you're feeling adventurous, PRs are welcome. :]

**Comment by PrOF-kk** [comment]
Sure, I'll take a look at adding them.
Can we use 3.10-style union types `TopLevelNode | Node` or should we support ≤ 3.9 with `Union[TopLevelNode, None]` instead?

**Comment by kiwiz** [comment]
Let's use the latter to maximize compat.

**Comment by PrOF-kk** [comment]
Sure, I'll do it. Could you please rebase the branch?

**Comment by kiwiz** [comment]
Done. :+1:

**Comment by PrOF-kk** [comment]
Missed 2 `raise_from` @ [L1820](https://github.com/kiwiz/gkeepapi/blob/deprecate_py2/gkeepapi/node.py#L1820) and [L1929](https://github.com/kiwiz/gkeepapi/blob/deprecate_py2/gkeepapi/node.py#L1929)

**Comment by kiwiz** [comment]
Thanks, pushed up fixes.

**Comment by kiwiz** [comment]
> Keep::login
Hmm, these probably shouldn't return anything. In the interest of preserving backwards compat, let's not document the return value, but keep them for now. The `if` statements can probably be removed.
> RemindersAPI
Good eye. The reminders functionality doesn't work atm, but I would rename the second `update` to `sync`.

**Comment by kiwiz** [comment]
Tracking in #130
