### ISSUE TITLE
ValueError: 'DEFAULT' is not a valid CheckedListItemsPolicyValue

### ISSUE THREAD

**Issue by sid-kap** [kiwiz/gkeepapi#12]
I'm getting the following error when calling keep.login():

```
  File "/home/sidharth/.local/share/virtualenvs/book-notes-downloader-2kIMB8p_/lib/python3.6/site-packages/gkeepapi/node.py", line 645, in load
    self._checked_listitems_policy = CheckedListItemsPolicyValue(raw['checkedListItemsPolicy'])
  File "/home/sidharth/.local/share/virtualenvs/book-notes-downloader-2kIMB8p_/lib/python3.6/enum.py", line 291, in __call__
    return cls.__new__(cls, value)
  File "/home/sidharth/.local/share/virtualenvs/book-notes-downloader-2kIMB8p_/lib/python3.6/enum.py", line 533, in __new__
    return cls._missing_(value)
  File "/home/sidharth/.local/share/virtualenvs/book-notes-downloader-2kIMB8p_/lib/python3.6/enum.py", line 546, in _missing_
    raise ValueError("%r is not a valid %s" % (value, cls.__name__))
ValueError: 'DEFAULT' is not a valid CheckedListItemsPolicyValue
```

It appears that `raw['checkedListItemsPolicy']` is "DEFAULT", but the current code allows only the value GRAVEYARD.

Do you know why this might be?

**Version:** current master branch.

**Comment by kiwiz** [comment]
@sid-kap I've added `DEFAULT` as a possible value. I believe `CheckedListItemsPolicy` defines where items go when you check them. During testing, I only ever saw `GRAVEYARD` so I only implemented that.

Can you check if master fixes the issue?

**Comment by sid-kap** [comment]
Thanks for responding so quickly! 

That issue is fixed. However, now I'm getting another error at [node.py, line 1301](https://github.com/kiwiz/gkeepapi/blob/3a3d0a142df8141888f3ce3068885554e3088659/gkeepapi/node.py#L1301):

```
    blob = cls()  
TypeError: 'BlobType' object is not callable     
```

Do you know why this might be happening?

**Comment by kiwiz** [comment]
Should be fixed with ^.

**Comment by sid-kap** [comment]
Now I'm getting this error:
```
    cls = self._blob_type_map[BlobType(_type)]
NameError: name 'self' is not defined
```
This is a class method, so self is not defined.

**Comment by kiwiz** [comment]
That's what I get for pushing that without testing. This final commit should do the trick.

**Comment by sid-kap** [comment]
That worked, thanks!!
