### ISSUE TITLE
Forcing Keep to get input updates periodically

### ISSUE THREAD

**Issue by antoniokhang97** [kiwiz/gkeepapi#121]
Hi there,
Firstly, thanks so much for anyone contributing to build this source code. It is tremendously helpful for my personal project that I'm working on. 
I have a question regarding the Keep's synchronization. Is there a way that I can force keep to be refreshed or get synced every 10 or 20 seconds? It takes like almost one minute to see users' collaboration input updates which is kind of long for my use case scenario. I've tried run "keep.sync()" in a while loop with "time.sleep(20.0)" but could not get the desired result. Any feedback would be appreciated! 
Thanks,

**Comment by kiwiz** [comment]
`keep.sync` should immediately fetch any updates. Can you check if the WebUI has the same delay?
