### ISSUE TITLE
Labeled notes not found

### ISSUE THREAD

**Issue by jaguarondi** [kiwiz/gkeepapi#13]
It looks like the 'labels' parameter doesn't work for find here. The label is found but not the notes.

```
In [131]: keep.findLabel('Work')
Out[131]: <gkeepapi.node.Label at 0x103a567f0>

In [132]: list(keep.find(labels=[keep.findLabel('Work')]))
Out[132]: []
```

**Comment by kiwiz** [comment]
Thanks for the bug report. Fixed and pushed to pypi (ver 0.10.2)
