### ISSUE TITLE
How to parameterize the color in gkeepapi.node.ColorValue.Yellow ?

### ISSUE THREAD

**Issue by haisamido** [kiwiz/gkeepapi#139]
I want to parameterize Yellow, as in `_color='Yellow'` and then use it like this:

`note.color = "gkeepapi.node.ColorValue."+_color`

but when I do that I get:
```bash
  File "/usr/local/lib/python3.10/site-packages/gkeepapi/node.py", line 1206, in save
    ret['color'] = self._color.value
AttributeError: 'str' object has no attribute 'value'
```

**Comment by kiwiz** [comment]
`ColorValue` is an enum, so you can do `ColorValue(color)`
