### ISSUE TITLE
Specify creation time and last modified time

### ISSUE THREAD

**Issue by wedgiebee** [kiwiz/gkeepapi#140]
With keep.createNote, is there a way to pass in a specific "creation time" and "last modified time"?

**Comment by kiwiz** [comment]
There is a `timestamps` attribute on the created note: https://gkeepapi.readthedocs.io/en/latest/#timestamps. However, (if memory serves) it isn't respected by the server.

**Comment by wedgiebee** [comment]
Ahhh, too bad. Thanks for your help!
