### ISSUE TITLE
Checking for success ?

### ISSUE THREAD

**Issue by simonmcnair** [kiwiz/gkeepapi#145]
Hi,
I've had a look around, and I was just wondering what the easiest way to check for success is ?  If I have created a note, and sync'd it, how do I know it was successfully sync'd ?  I don't see any properties or return for the keep.sync() method ?

Cheers
Simon

**Comment by kiwiz** [comment]
Notes have an `id` attribute. You can check whether a `keep.get` call for that ID returns the note afterwards.
