### ISSUE TITLE
Use with Akiflow? 

### ISSUE THREAD

**Issue by smitpau** [kiwiz/gkeepapi#146]
Hi, 

Firstly apologies this is a question so I realise it shouldn't be in the issues section but not sure where else to raise it.

I am relatively new to API's so would appreciate it if someone could please explain if it should be possible to use this unofficial API so I can view my Keep notes in Akiflow which can use Zapier & IFTTT as connectors. 

Any help is appreciated (unfortunately can't use the official API as I don't have an Enterprise account). 

Thanks

**Comment by kyrlon** [comment]
Is there an API available using Akiflow?

**Comment by kiwiz** [comment]
It looks like Akiflow supports API access, so it would be possible to use this library. You'd need to write some Python code and keep it running somewhere, though.
