### ISSUE TITLE
The links in exception.LoginException FAQ are dead

### ISSUE THREAD

**Issue by ooker777** [kiwiz/gkeepapi#149]
Full text:

> I get a “NeedsBrowser”, “CaptchaRequired” or “BadAuthentication” exception.LoginException when I try to log in.
> 
> This usually occurs when Google thinks the login request looks suspicious. Here are some steps you can take to resolve this:
> 
> 1. Make sure you have the newest version of gkeepapi installed.
> 2. Instead of logging in every time, cache the authentication token and reuse it on subsequent runs. See [here](https://github.com/kiwiz/keep-cli/blob/master/keep#L106-L128) for an example implementation.
> 3. If you have 2-Step Verification turned on, generating an App Password for gkeepapi is highly recommended.
> 4. Allowing access through this [link](https://accounts.google.com/DisplayUnlockCaptcha) has worked for some people.
> 5. Upgrading to a newer version of Python (3.7+) has worked for some people. See this [issue](https://gitlab.com/AuroraOSS/AuroraStore/issues/217#note_249390026) for more information.
> 6. If all else fails, try testing gkeepapi on a separate IP address and/or user to see if you can isolate the problem.

- This link in 2 is dead: https://github.com/kiwiz/keep-cli/blob/master/keep#L106-L128
- The link in 4 returns:

> 
> This website is no longer available
> 
> To better protect your account, Google no longer allows account access with this website.
> 
> If you have trouble signing in, try again from a familiar device or location.

**Comment by kiwiz** [comment]
Thanks, resolved in a working branch.

**Comment by ooker777** [comment]
which branch? I see that recently you have updated the doc but the links are untouched

**Comment by kiwiz** [comment]
Ah, ReadTheDocs builds are currently broken. I'll get that fixed.
