### ISSUE TITLE
Migrated Assistant Notes raise KeyError: 'title' on resume

### ISSUE THREAD

**Issue by PrOF-kk** [kiwiz/gkeepapi#152]
Please make sure you've done the following before submitting your issue:

- [x] Check that you're running the newest version of the library.
- [x] If you're providing a stack trace, make sure it doesn't contain your password.
- [x] If you're getting a KeyError or ParseException, please follow the instructions [here](https://gkeepapi.readthedocs.io/en/latest/#reporting-errors) to dump the raw data.

Additionally, please provide the following information:

- Operating system: Windows 10 22H2
- Python version :  3.11.0
---
<details><summary>Raw data from print(e.raw)</summary>
<pre>
{
   "webLink":{
      "kind":"notes#webLink",
      "url":"https://support.google.com/keep/?p=migrated_from_assistant",
      "provenanceUrl":"https://support.google.com/keep/?p=migrated_from_assistant",
      "hasThumbnailUrl":true
   }
}
</pre>
</details>

Calling code can be found at
https://github.com/PrOF-kk/rainmeter-gkeep/blob/115a1f443372cdb4208eafe532508db6b9461543/Skins/Keep/Keep.py#L40

**Comment by viertel97** [comment]
I can confirm this. For me the error occurs at the `gkeepapi.Keep().login(GOOGLE_E_MAIL, GOOGLE_APP_PASSWORD, device_id=GOOGLE_DEVICE_ID)`.
