### ISSUE TITLE
Is this safe?

### ISSUE THREAD

**Issue by will-ca** [kiwiz/gkeepapi#154]
I accidentally clicked a button that instantaneously modified the state of thousands of notes. (Not sure what exactly, but I assume CTRL+A, thinking I was in a text box, followed by trying to type, and pressing one of the single-letter hotkeys for Archive/Delete.)

I would like to be able to to undo that accident, using the state of a Takeout archive as reference.

Would I be risking my Google account by doing so?

I.E., Is there any precedent or statement of Google disabling an account because of use of `gkeepapi`?

**Comment by kiwiz** [comment]
Not to my knowledge. You might hit rate limits, so I'd recommend making your code idempotent and/or adding retry logic

**Comment by will-ca** [comment]
Cool. Well, I guess there's enough users of both this and downstream projects to trust we'd hear about it.

Sounds like a sensible precaution, and thanks for the quick response!
