### ISSUE TITLE
Notes are created out of order

### ISSUE THREAD

**Issue by yuvgin** [kiwiz/gkeepapi#157]
I'm using gkeepapi to transfer notes into keep from another note app.

I have a dataframe of ~1000 notes that I iterate over. The dataframe is sorted by creation date (of the original notes) but when I sync they appear in keep in the wrong order (despite the fact that the node's timestamps are in the correct order). 
Any idea what's going on? 

Running on Ubuntu with python 3.7

**Comment by kiwiz** [comment]
I believe there are two issues here:

* Timestamps (IIRC) are not honored - the value is set by the server when a new note is synced
* There is no guarantee of order when more than one node is synced to the server

For the behaviour you desire, you might have to call `sync()` after every new note.

**Comment by yuvgin** [comment]
Thanks for the quick reply.
I tried syncing after every createNote, and also tried adding time.sleep after every sync. Didn't do the trick..

**Comment by kiwiz** [comment]
Oh, I understand now. The sorting of notes is defined via the `sort` attribute on notes, which is randomly generated. You can set it to a monotonically increasing/decreasing value:

```python
for i, blah in enumerate(items):
    note = keep.createNote()
    note.sort = i
    ...
```

**Comment by yuvgin** [comment]
That works, thanks!!
Perhaps add it to the docs, it seems important :)
