### ISSUE TITLE
gkeepapi.LoginException: Not logged in

### ISSUE THREAD

**Issue by arunk140** [kiwiz/gkeepapi#2]
I can't seem to Login I **Keep** getting this `gkeepapi.LoginException: Not logged in` Exception

```
Traceback (most recent call last):
  File "keep.py", line 45, in <module>
    keep.sync()
  File "/Library/Python/2.7/site-packages/gkeepapi/__init__.py", line 449, in sync
    labels=[i.save() for i in self._labels.values()] if labels_updated else None,
  File "/Library/Python/2.7/site-packages/gkeepapi/__init__.py", line 211, in changes
    json=params
  File "/Library/Python/2.7/site-packages/gkeepapi/__init__.py", line 131, in send
    raise LoginException('Not logged in')
gkeepapi.LoginException: Not logged in
```
Am I missing something?

Edit: Tried adding delay after Login using `time.sleep(10)`, Still got the same exception.

**Comment by kiwiz** [comment]
Is 2factor enabled on the account? Can you show the code you're using?

**Comment by lopespaz** [comment]
I'm facing the same. The code:

```
import gkeepapi

keep = gkeepapi.Keep()

success = keep.login('', '')

keep.sync()

```

**Comment by lopespaz** [comment]
You can try this:

- Activate the 2 step login
- Generate an app password: https://support.google.com/accounts/answer/185833?hl=en&ctx=ch_b%2F0%2FSmsAuthSettings
- Use the app password to login

This worked for me.

Good luck.

**Comment by kiwiz** [comment]
Note added about Twofactor in 9c568562d9eff6363d518a8ef0f5f644d6a9fc6b.

**Comment by arunk140** [comment]
I did not have Two Factor Authentication initially, to fix this I did have to activate it and generate an App Password.

Thanks kiwiz and lopespaz

**Comment by kiwiz** [comment]
Odd, I'd expect this to work without TwoFactor. If you fancy doing some more debugging, can you check what this code returns?

```
import gpsoauth

ret = gpsoauth.perform_master_login('your_username', 'your_password', '')
print 'Token' in ret
```

**Comment by arunk140** [comment]
It returns "True"
