### ISSUE TITLE
what is the ordering of elements in List.items?

### ISSUE THREAD

**Issue by buyuk-dev** [kiwiz/gkeepapi#27]
Its undocumented, and I could not find a reliable way to access elements of a list in exact same order as they are visible in the google keep.  I tried sorting them by Node.sort property but it doesn't work for all my lists. Is there any proper way to achieve it in current version of api?

**Comment by buyuk-dev** [comment]
okey, i didnt notice that sort property is a string representation of an integer, so whilst i thought that its sorted numerically it was actually sorted alphabetically. When i converted it to integer it worked fine.

**Comment by buyuk-dev** [comment]
perhaps we could add this conversion to api permanently? Or even go one step further and sort items by it immediately.

**Comment by kiwiz** [comment]
Pushed up 0.10.8 to sort items
