### ISSUE TITLE
Keep.createLabel() lowercases the label name

### ISSUE THREAD

**Issue by evandeaubl** [kiwiz/gkeepapi#29]
Version: default from pip

When I create a label using the Keep.createLabel method, the label name is lowercased when I pull up the Keep webapp.

Reproducer:

```
import gkeepapi

keep = gkeepapi.Keep()
success = keep.login(...)

label = keep.createLabel('RandomKeep')

keep.sync()
```

Pull up web interface, and label is named "randomkeep".

**Comment by kiwiz** [comment]
Uploaded 0.10.8 to pip which has a fix for this.

**Comment by evandeaubl** [comment]
Confirmed the fix this morning. Thank you very much!
