### ISSUE TITLE
keep.get() displays "None"

### ISSUE THREAD

**Issue by 2hands10fingers** [kiwiz/gkeepapi#3]
I'm using this for the first time, but having poor results.

```
import gkeepapi

keep = gkeepapi.Keep()
keep.login(username, password)


gnote = keep.get('15fb415844b.8224185fe3855046')

print(gnote)

```

This produces "None" when there's definitely stuff in that note.

**Comment by kiwiz** [comment]
Does `keep.all()` return this note in the list? Is there anything unique about this note? (Is it shared?)

**Comment by 2hands10fingers** [comment]
Thank you for replying, @kiwiz 

`keep.all()` returns nothing.
 
All the note has in it is:
```
Nationwide - change address
Change address on phone bill
Paystubs
```

The note is not shared. Nothing unique.

**Comment by kiwiz** [comment]
Odd. Can you hop on gitter (https://gitter.im/gkeepapi/Lobby) for some debugging?

**Comment by 2hands10fingers** [comment]
@kiwiz Sure thing. I'm in there now.

**Comment by 2hands10fingers** [comment]
This issue has been solved. Glad to debug with you.
