### ISSUE TITLE
calling "url()" results in "TypeError: must be str, not NodeType"

### ISSUE THREAD

**Issue by mattmarano** [kiwiz/gkeepapi#30]
I believe this could be resolved by changing "self._TYPE" to "self._TYPE.value" in the following line:
https://github.com/kiwiz/gkeepapi/blob/a46ae07eb5f7e991d5bc113ca4719793e954a9cf/gkeepapi/node.py#L1106

**Comment by kiwiz** [comment]
Fixed, thanks.
