### ISSUE TITLE
Login Exception

### ISSUE THREAD

**Issue by etatus** [kiwiz/gkeepapi#32]
When trying keep.login I get the following error:

gkeepapi.exception.LoginException: (u'NeedsBrowser', u'To access your account, you must sign in on the web. Touch Next to start browser sign-in.')

I am running the script from Raspbian with Python 2.7.9.

**Comment by etatus** [comment]
Ok, I found a way to solve this problem in the Raspberry (via console). 

1. You have to open the following link with lynx (an Internet text browser): https://accounts.google.com/b/0/DisplayUnlockCaptcha
2. Authenticate with your google account credentials
3. Authorize the device/MAC (the Raspberry) to access your account
4. You can now use your login/password in keep.login function

**Comment by etatus** [comment]
I finally found a way to make persisent the authentication. You have to activate the 2 factor authentication in your Google account and then you have to create an application password for gkeepapi from: https://myaccount.google.com/apppasswords

Then you have to use the application password instead your usual password in keep.login function (the username is the same).

**Comment by kiwiz** [comment]
Clarified note in readme.
