### ISSUE TITLE
Created & Updated Timestamps overwritten by server 

### ISSUE THREAD

**Issue by mleventis** [kiwiz/gkeepapi#33]
Hi,

If i created a note locally at 11:22, and synced it at 11:24, the server will record 11:24 as creation time. It seems to ignore the create & update timestamps sent by gkeepapi.

Example code to reproduce the problem : 

```
import gkeepapi
import time

keep = gkeepapi.Keep()
keep.login('XXXXXXXX@gmail.com', 'YYYYYYYYY')

keep.createNote('Title', 'Text')

print("SLEEP")
time.sleep(120)

keep.sync()

print("DONE")
```

I dumped the outgoing http requests sent by the changes() function of KeepAPI, and the timestamps were right (they were at 11:22). But the server didn't take them into account.

If i intercept the sync request and modify the timestamps, to set them one hour ago for example, i see that the server clearly ignores them.

Timestamps accuracy is important for my use of gkeepapi. Any clue ? Thanks !

**Comment by kiwiz** [comment]
Unfortunately, I don't think there's a way to manipulate the timestamps. IDs are generated client-side, so in theory, you could embed your "created" timestamp there and use that.

**Comment by mleventis** [comment]
Thanks for your quick answer ! Ok i get it.
