### ISSUE TITLE
Support sub-items inside lists 

### ISSUE THREAD

**Issue by mgckind** [kiwiz/gkeepapi#35]
Very nice api! 
I've been working on a little CLI mostly for myself https://github.com/mgckind/keepcli based on your excellent work.
Recently, Google Keep supports nested lists. Is there a plan to add  this?
Thanks!

**Comment by kiwiz** [comment]
Thx! `gkeepapi` already does the bookkeeping internally (ea5a8f16a9c3bb85b4d73b4dd05fd3a35255f019), but I'm debating how to expose this. Sub-items are technically still children of the `List` object, just with a `superListItemId` field set to the parent item. There are also UX decisions to consider (ex: The first item in a list can't be indented). Thoughts or code welcome!

Nice job with `keepcli`. I'm working on something similar, though I'm taking a slightly different approach: https://github.com/kiwiz/keep-cli. I added cache support recently, so this might be useful for your offline mode: https://gkeepapi.readthedocs.io/en/latest/#caching-notes. Warning: The `dirty` state of notes is persisted when serialized. This has implications if you make changes and serialize the data without syncing. Upon reloading the application, the next sync will immediately push up those changes (which could be potentially surprising).

**Comment by mgckind** [comment]
Thanks!, didn't see the commit. I have no current thoughts on this, in the web interface when you check the top item all the sub-items get checked as well. For the cli might be less tricky than the API itself :)

I wasn't aware of your other work, I completely missed it and picked a very similar name, sorry about that. 
I had a cli for another project and pretty much adapted it as a need as I have always a terminal open (and working on remote machines)

Thanks for the tip on cached support, my work around was to pickle the content into a file but didn't fully tested it, I'll take a look soon.

**Comment by kiwiz** [comment]
No worries. I added support for indenting items: https://gkeepapi.readthedocs.io/en/latest/#indent-dedent-list-items. Lemme know how that works.
