### ISSUE TITLE
 No module named 'gkeepapi'

### ISSUE THREAD

**Issue by lostdinar2** [kiwiz/gkeepapi#39]
Hello everyone.I have installed gkeepapi module by using pip install gkeepapi.But I still get  "No module named 'gkeepapi'" error.
```
import gkeepapi
import getpass
keep = gkeepapi.Keep()
success = keep.login('**@**','**')
labels = keep.labels()
gnotes = keep.find(labels=["activevocabulary"])
for x in gnotes:
    print(x.text)
```
I am using python 3.6.5 and IDLE.
I installed pip3 on Ubuntu and checked:
```
q@q-ABRA-A5-V12-1:~$ pip3 --version
pip 9.0.1 from /usr/lib/python3/dist-packages (python 3.6)
```

I installed with gkeepapi with pip3:
`pip3 install gkeepapi`

But I still get the same error:

> ========================== RESTART: /home/q/s.py ==========================
> Traceback (most recent call last):
>   File "/home/q/s.py", line 1, in <module>
>     import gkeepapi
> ModuleNotFoundError: No module named 'gkeepapi'
>

**Comment by kiwiz** [comment]
`pip3 install gkeepapi` might do the job.
