### ISSUE TITLE
Unknown blob type: None

### ISSUE THREAD

**Issue by repomorphic** [kiwiz/gkeepapi#42]
I am trying to run the following code on linux Ubuntu with IDLE .When I compile and run this code I get "Unknown blob type: None" error.

```
import gkeepapi
import getpass

keep = gkeepapi.Keep()
success = keep.login('@gmail.com','****')
labels = keep.labels()
gnotes = keep.find(labels=["grammar"])

for x in gnotes:
    print(x.text)
```

> RESTART: /home/q/s.py 
> Unknown blob type: None
> 

How can I fix this error?

**Comment by kiwiz** [comment]
@lostdinar2 can you provide some additional information via the instructions [here](https://gkeepapi.readthedocs.io/en/latest/#reporting-errors)?

**Comment by kiwiz** [comment]
Closed due to inactivity.

**Comment by kwcooper** [comment]
I'm also getting `Unknown blob type: None` which is thrown after I use `keep.resume()`. That said the api still seems to be working fine, but the error still persists.

**Comment by kiwiz** [comment]
@kwcooper Can you try with the newest version (0.11.3)? If it still occurs, we can try debugging further.

**Comment by kanihal** [comment]
I'm still getting `Unknown blob type: None` even with version  `0.11.5`

**Comment by kiwiz** [comment]
@kanihal is this after calling `resume`?

**Comment by kanihal** [comment]
@kiwiz 
Nope, I was trying the example mentioned in the readme file and had put print statements to determine which statement was printing the `Unknown blob type: None`, it's getting printed after `keep.login()`
```
import gkeepapi

keep = gkeepapi.Keep()
success = keep.login('...', '...')
^^^ THE WARNING GETS PRINTED HERE

note = keep.createNote('Todo', 'Eat breakfast')
note.pinned = True
note.color = gkeepapi.node.ColorValue.Red
keep.sync()
```

Although I did get the new note added to my google keeps.

**Comment by kiwiz** [comment]
@kanihal Can you try the instructions [here](https://gkeepapi.readthedocs.io/en/latest/#reporting-errors) and see if that surfaces any other info?

**Comment by funktionzero** [comment]
Hi everyone. Same error here, upon login. The defective node in its raw form:
```
{
   "kind":"notes#node",
   "id":"1498648454675.218531217",
   "serverId":"18Piwi207odMGmoRumcWOrow_CRP_lS4zXFevjDdWJ7jgbkzjT_cYIPGeN8NNxQ",
   "parentId":"15cabe21c1a.8d12a4fca46145cb",
   "parentServerId":"16d7fRL8JDyzHmkYLS7CxFwcWm1aovFxAJK7y9tFoeD7REX15wlN_KYiBNqR3b0Nr_qdj",
   "type":"BLOB",
   "timestamps":{
      "kind":"notes#timestamps",
      "created":"2017-06-28T11:14:14.675Z",
      "updated":"2018-05-03T10:20:43.928Z",
      "deleted":"1970-01-01T00:00:00.000Z"
   },
   "blob":{
      "kind":"notes#blob",
      "mimetype":""
   },
   "nodeSettings":{
      "newListItemPlacement":"BOTTOM",
      "checkedListItemsPolicy":"GRAVEYARD",
      "graveyardState":"EXPANDED"
   },
   "annotationsGroup":{
      "kind":"notes#annotationsGroup"
   }
}
```
I'd be happy to provide more info if needed.

**Comment by kiwiz** [comment]
@funktionzero Thanks, that was very helpful! Pushed up a fix.
