### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute error when using .get

### ISSUE THREAD

**Issue by wahlfeld** [kiwiz/gkeepapi#47]
I can't seem to get `keep.get` to work. I've tried using the ID in the note URL as per the docs but I keep getting the error below:

`note = keep.get('<ID>')`
`print note.title`
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'NoneType' object has no attribute 'title'`

Doing a `print keep.all()` returns note IDs in hex form but they also don't work:

`print keep.all()`
`[<gkeepapi.node.Note object at 0x103268c90>, <gkeepapi.node.Note object at 0x1032796d0>]`

**Comment by wahlfeld** [comment]
So it looks like Google has swapped the note `id` with the `serverId` in the URL. I had to [dump the state](https://gkeepapi.readthedocs.io/en/latest/#caching-notes) to reveal the actual note IDs which then work fine with `.get`. I think you just need to update the docs so people know to do this in order to figure out what the note IDs are.

**Comment by kiwiz** [comment]
Thanks for the note. Reopening for now while I figure out how to resolve this.

**Comment by kiwiz** [comment]
Fixed as of 8899132.
