### ISSUE TITLE
Image in notes & selective download by search.

### ISSUE THREAD

**Issue by charlesinc3** [kiwiz/gkeepapi#49]
Images in notes are not fetched after Keep.login().  Will this be added ? 

It seems search works on local note caches. Do we have scaling concerns with large number of notes ? Is there a way to download notes based on search criterions, e.g,  notes created/updated in last week. (or after certain days).

**Comment by kiwiz** [comment]
Media retrieval is a WIP - there's currently no timeline on when it will get done.

To speed up load, you can try the suggestions here: https://gkeepapi.readthedocs.io/en/latest/#caching-notes

**Comment by kiwiz** [comment]
Scratch that, turned out to be much easier than I expected. You can grab media files like so: https://gkeepapi.readthedocs.io/en/latest/#getting-media

**Comment by charlesinc3** [comment]
Cool, works great!  Thanks for adding the support.
