### ISSUE TITLE
can't add label

### ISSUE THREAD

**Issue by jason79** [kiwiz/gkeepapi#52]
anybody having trouble adding labels? this code used to work. i am running the latest version of gkeepapi.

 File "C:\Users\jason\Google Drive\python\keep_calls2.py", line 35, in make_blank_calls
    note.labels.add('calls')
  File "C:\Python27\lib\site-packages\gkeepapi\node.py", line 838, in add
    self._labels[label.id] = label
AttributeError: 'str' object has no attribute 'id'

**Comment by kiwiz** [comment]
Sorry, the interface for manipulating labels has changed slightly. There's some docs on adding notes here: https://gkeepapi.readthedocs.io/en/latest/#manipulating-labels-on-notes
