### ISSUE TITLE
Would a Port to Google Apps Scripts be Possible?

### ISSUE THREAD

**Issue by stellarpower** [kiwiz/gkeepapi#56]
Hi,

I was rather hoping I might be able to port bits of the library to Google Apps Scripts, access to Keep is a sorely missed feature. I'd like to help however I realise I'm in a bit over my head as I don't have much experience with OAuth and I have too many projects on the go at the moment. As a first step I was hoping to rip out the tokens from the Python implementation, and then just separate the requests from the library and send them off with the tokens, refreshing if needed but on first appearances I assume I would need to port a significant amount of the `gpsoauth` library too. There is a node version but anyway, as I'm not familiar with the internal workings, do you think this would be feasible at all and is there any chance it could happen in the future?

Thanks

**Comment by kiwiz** [comment]
Should be possible as long as Apps scripts can fire off HTTP requests. A quick Google reveals [this](https://developers.google.com/apps-script/reference/url-fetch/url-fetch-app) page, which looks promising.

**Comment by kiwiz** [comment]
To clarify, I'd be willing to provide pointers on a GApps Script port, but I don't have the time to write or maintain it. I'd recommend starting with a JS/node version and then seeing if you could write a shim for the way GApps Scripts do HTTP requests. Feel free to ping me on gitter with any questions!
