### ISSUE TITLE
Cannot modify shared note

### ISSUE THREAD

**Issue by shadow7412** [kiwiz/gkeepapi#57]
Please make sure you've done the following before submitting your issue:

- [X] Check that you're running the newest version of the library.
gkeepapi==0.11.3
- [X] If you're providing a stack trace, make sure it doesn't contain your password.
N/A
- [X] If you're getting a KeyError or ParseException, please follow the instructions [here](https://gkeepapi.readthedocs.io/en/latest/#reporting-errors) to dump the raw data.
N/A

Reproduction Steps:

1. Have a friend.
2. Get them to share a note with you (I was using a checklist)
3. Attempt to modify that note

Expected Behaviour:

The note should be altered.

Observed Response:

The note was not modified - but the sync function seemed to complete successfully.

**Comment by kiwiz** [comment]
Thanks for the bug report. I experimented with the functionality and I did encounter some odd behaviour. All tests were done with the sharee (the account that was shared to).

What worked:
- Updating notes (title / text)
- Updating list title
- Deleting list items
- Updating list items (text / checked)

What didn't work:
- Creating new list entries
Additionally, I noticed that the server responds poorly to rapid updates to list items. I'd occasionally get errors or find that the server had rolled back my changes. I only noticed this when the sharer had the list open (and was actively pulling updates).

**Comment by shadow7412** [comment]
I'm glad to hear it's reproducible.

I've currently worked around the problem by creating a new list, owning it, and sharing my version, so it's not that difficult to work around.

I haven't seen the last issue you mentioned, but I only add/check/uncheck one item at a time, so I doubt I'd run into it.

**Comment by kiwiz** [comment]
Hi, I've uploaded v0.11.4 which should fix this problem.

**Comment by shadow7412** [comment]
Fix confirmed - thanks for your prompt response 🥇
