### ISSUE TITLE
Reduce sign in time

### ISSUE THREAD

**Issue by manu354** [kiwiz/gkeepapi#59]
Hey,

I live in Sydney, Australia, and signing in can often take up to 6 or 7 seconds. I was wondering if this could possibly be due to gkeepapi only communicating with US authentication servers. If this is the case, an optional setting to change this would be great.

I am happy to implement this myself if someone can point me in the right direction.

Thanks 😄

**Comment by kiwiz** [comment]
Do you have a large number of notes? Caching the notes as documented [here](https://gkeepapi.readthedocs.io/en/latest#caching-notes) might help.

**Comment by kiwiz** [comment]
Closing this tix because there isn't a better suggestion atm.

**Comment by Jonta** [comment]
@kiwiz Do you have an MVP for this?

It takes around 16 seconds here, with or without the cache-lines
```
import gkeepapi    
import simplejson as json    
     
keep = gkeepapi.Keep()    
keep.login('emailaddress@here.com', 'password-is-here')    
     
# Store cache    
state = keep.dump()    
fh = open('state', 'w')    
json.dump(state, fh)    
     
# Load cache               
fh = open('state', 'r')    
state = json.load(fh)    
keep.restore(state)        
                           
gnote = keep.get('note-ID-is-here')         
print(gnote)
```
I only need it to read this one note, no need to sync

16 seconds even if I just

```
import gkeepapi
     
keep = gkeepapi.Keep()    
keep.login('emailaddress@here.com', 'password-is-here')
```
Note the lack of `gnote = keep.get('note-ID-is-here')`. Adding it at the end doesn't significantly change the time it takes to run

**Comment by kiwiz** [comment]
You should load the cache before calling `Keep.login` and only save to the cache at the very end of your code. For an example, see https://github.com/kiwiz/keep-cli/blob/master/keep#L112

**Comment by Jonta** [comment]
Doing so makes sense, but where is that cache stored?

I'm running this as part of a shell script that runs a few times a day. Having the cache update periodically would make sense though

The 135 lines you linked to are a lot to take in. I don't even know what `fh` in the cache-example means
