### ISSUE TITLE
Parse error in <class 'gkeepapi.node.NodeAudio'>

### ISSUE THREAD

**Issue by sonofhypnos** [kiwiz/gkeepapi#60]
I am not able to sync my data during the login.
It seems to have something to do with the audionotes I made recently. I suspect they didn't get recorded correctly.

Here is my code:

import gkeepapi
keep = gkeepapi.Keep()
keep.login(...)

My Error:
KeyError: 'length'
The above exception was the direct cause of the following exception:
ParseException: Parse error in <class 'gkeepapi.node.NodeAudio'>

Raw Data:
{'kind': 'notes#blob', 'type': 'AUDIO', 'mimetype': 'audio/3gpp', 'byte_size': 14342, 'is_uploaded': True}

**Comment by kiwiz** [comment]
Should be fixed via the above commit.

**Comment by sonofhypnos** [comment]
Thank you so much!
