### ISSUE TITLE
Parse error in <class 'gkeepapi.node.NodeDrawingInfo'>

### ISSUE THREAD

**Issue by funktionzero** [kiwiz/gkeepapi#61]
Hello. First approach to this project.

I get an error when executing `keep.login('...','...')`:
```
gkeepapi.exception.ParseException: Parse error in <class 'gkeepapi.node.NodeDrawingInfo'>
```
Raw exception prints:
```
{
   u'drawingId':u'1IWjUgVocgWLzF2E42p-xhKfhwwEfUln2DQ',
   u'snapshotData':{
      u'mimetype':u'image/png',
      u'extracted_text':u'',
      u'kind':u'notes#blob',
      u'type':u'IMAGE',
      u'extraction_status':u'DO_NOT_PROCESS'
   }
}
```
Anything useful to you? Let me know if I can help you further debug this. I'm new to Python, but I know my way around code. Thanks!

**Comment by kiwiz** [comment]
Thanks for the report! I've pushed up a fix that should hopefully resolve the issue. Can you try it out and see if everything looks good?

**Comment by funktionzero** [comment]
Noice! It worked. Now it's just a warning showing up:
```
No handlers could be found for logger "gkeepapi.node"
True
```
...but I think you already know / it's nothing important.

Cheers and thanks again.

**Comment by kiwiz** [comment]
Hmm, the former is expected but not the latter. Is it possible something in your code is doing that?

**Comment by funktionzero** [comment]
No such thing as "my code", I think.  I'm simply following the tutorial and typing into the Python (2.7) console. Hey, whatever.

**Comment by kiwiz** [comment]
Ah, it sounds like the console was just emitting the return code of `keep.login()`. :+1:
