### ISSUE TITLE
my notes sync out of order

### ISSUE THREAD

**Issue by nthsamir** [kiwiz/gkeepapi#65]
import gkeepapi;
keep=gkeepapi.Keep()
keep.login('user,'apppassword')
for i in range(0,6):
   notea= keep.createNote(str(i));
   keep.sync()

**Comment by kiwiz** [comment]
Hi there, could you provide some more info about what you expect?

**Comment by nthsamir** [comment]
Sure. 
I use google keep as a task manager. So everyday has its own checklist with the date as a title. I was trying to automate the process of creating those notes for 4 weeks at a time. Here's a screen shot of the code. 

![Annotation 2019-05-02 114052](https://user-images.githubusercontent.com/45188344/57088152-a728a680-6ccf-11e9-8241-7ceb356daaaa.png)
![Annotation 2019-05-02 114401](https://user-images.githubusercontent.com/45188344/57088153-a728a680-6ccf-11e9-8217-0480db17b352.png)

**Comment by nthsamir** [comment]
•messed around with the sort id after pulling the json data and seeing what contributed to the order
•probably should have read the documentation
•if anyone can improve on this, or notices something wrong, do help, I'm new
`import gkeepapi
import os
import time
keep=gkeepapi.Keep()
keep.login(os.environ.get('gkeepapi_user'),os.environ.get('gkeepapi_password'))

def suffix(a):
    if(a!=11 and a%10==1):suffix='st'
    elif(a!=12 and a%10==2):suffix='nd'
    elif(a!=13 and a%10==3):suffix='rd'
    else: suffix='th'
    return suffix

from datetime import date, timedelta
days = ['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday']
months= ['January', 'Feburary','March','April','May','June','July','August','September','October','November','December']

start= date.today()
note1=keep.createNote(days[start.weekday()]+', '+months[start.month-1]+' '+str(start.day)+suffix(start.day)+', '+str(start.year))
id1=note1.sort

duration=24
for i in range (1,duration):
    now=start+timedelta(i)
    note2=keep.createNote(days[now.weekday()]+', '+months[now.month-1]+' '+str(now.day)+suffix(now.day)+', '+str(now.year))
    note2.sort=id1 - i
    keep.sync()
    time.sleep(1)`

**Comment by nthsamir** [comment]
fixed by messing around with the sortID inside the loop after grabbing the first one

**Comment by nthsamir** [comment]
![image](https://user-images.githubusercontent.com/45188344/58343933-531e6700-7e22-11e9-9c00-106b52c35553.png)

**Comment by nthsamir** [comment]
I'm closing the issue but if anyone sees a way to make this better/faster do comment
