### ISSUE TITLE
List items out of order in created list

### ISSUE THREAD

**Issue by Stefan-Markus** [kiwiz/gkeepapi#67]
When I create a list all the list items are in a completely random order. They're not sorted numerically or (as I would like) in the same order as the reference list used to create it.

First method used to create list:
```
newlistTitle = "To-Do Testday"
newlistContent = dictionarytest['To-Do Monday']
glist = keep.createList(newlistTitle,newlistContent)
keep.sync()
```
Second method used to create list:
```
newlistTitle = "To-Do Testday"
glist = keep.createList(newlistTitle)
newlistContent = dictionarytest['To-Do Monday']
for n in newlistContent:
    text=n[0]
    glist.add(text,False)
keep.sync()
```
Reference list (`dictionarytest['To-Do Monday']`):
```
[('9:00 Wake/Fold/Pills/Change', False),
 ('9:10 Dishwasher/Make Breakfast', False),
 ('9:15 Eat Breakfast/Youtube', False),
 ('9:30 Daily Hygiene', False),
 ('9:40 Exercise (15 Push-ups, 15 squats, 10 crunches)', False),
 ('9:45 ', False),
 ('1:00 Lunch Break', False),
 ('1:30', False),
 ('4:00 Garbage', False),
 ('4:30', False),
 ('6:00 Dinner', False),
 ('6:30', False),
 ('9:50 Make List for Tomorrow/Prep Stuff', False),
 ('10:00 Snack/Melatonin', False),
 ('11:00 Reading', False),
 ('11:30 Sleep', False)]
```
Screenshot of list that is created:
![image](https://user-images.githubusercontent.com/38923963/65470136-2e191f80-de27-11e9-8bc1-b59c5f0e6386.png)

What I want is for the created list to be in the same order as the reference list. Any help you could provide would be appreciated.

**Comment by kiwiz** [comment]
Hi, you can currently work around this by using the third argument of [add()](https://gkeepapi.readthedocs.io/en/latest/gkeepapi.html#gkeepapi.node.List.add). Assign increasing (or decreasing) `sort` values and you should get them in order. I'll change the default behaviour to be more intuitive soonish.

**Comment by Stefan-Markus** [comment]
Thank you so much, that fixed it. I'll close the issue now.

**Comment by kiwiz** [comment]
@Stefan-Markus Fwiw, I added the ability to place items at the [top or bottom](https://gkeepapi.readthedocs.io/en/latest/index.html#setting-list-content).

Some technical details:
This requires looping through the list every time you add a new item (to compute the smallest/biggest sort value) so it's less efficient than specifying an index. Shouldn't matter if you're not creating gigantic lists, though.
