### ISSUE TITLE
keep.findLabel(str, create=True) lowercases label

### ISSUE THREAD

**Issue by darthwalsh** [kiwiz/gkeepapi#71]
Related to #29, but `keep.findLabel` has the same bug when creating a label, i.e. in

    keep.findLabel(args.label, create=True)

This line always lowercases the query string, which is used to create the label:
https://github.com/kiwiz/gkeepapi/blob/cf23ff85c27de6dd085dd932f582ffdaef9c5d68/gkeepapi/__init__.py#L770

---

- [X] Check that you're running the newest version of the library: 0.11.8
- N/A If you're providing a stack trace, make sure it doesn't contain your password.
- N/A If you're getting a KeyError or ParseException, please follow the instructions [here](https://gkeepapi.readthedocs.io/en/latest/#reporting-errors) to dump the raw data.

**Comment by kiwiz** [comment]
Afaik, this is expected because labels aren't case sensitive.

**Comment by darthwalsh** [comment]
Label equality is case insensitive like you say, but when you create a label in the web interface or `keep.createLabel()`, Keep shows you the same case you used to create (similar to the way the Windows file system allows for accessing files using either case, but shows you the case you used to create the label).

So `keep.findLabel('MyIdea', create=True)` should return label "myidea" if it exists, but if it doesn't exist it should create label "MyIdea".

#29 had this same issue.

**Comment by kiwiz** [comment]
Ack, thanks for clarifying. Fixed in `0.11.9`.
