### ISSUE TITLE
Can't work out how to get a note that is a list

### ISSUE THREAD

**Issue by WhatDoor** [kiwiz/gkeepapi#74]
Hi, 

I'm not sure if I understand the docs correctly, but I am trying to use keep.get('XXX') to get a note that is a list. I managed to get it working for regular notes, but for some reason i can't get lists.

Any help would be appreciated

**Comment by kiwiz** [comment]
Hi, `keep.get()` should work lists as well - I just tested and confirmed this. Can you provide any addn info?

**Comment by WhatDoor** [comment]
```
import gkeepapi
import keyring
import sys

user = 'WhatDoor@hotmail.com'
pw = keyring.get_password('google_keep', user)

keep = gkeepapi.Keep()
keep.login(user, pw)

listNode = keep.get('1y4oicjz_V1EIUwIumbDQPAI69m0zeMse7Yqq_Gg-mhhxmbqdI2NyarTruzqhBQ')

list = listNode.items

print(list[0].text)

keep.sync()

```
I'm not sure what you mean by addn info, but this is the script i am currently testing. When I run this, nothing happens, the script just gets stuck and doesn't terminate.

**Comment by WhatDoor** [comment]
Ah nevermind, I got it working - i was confused about where to add new entries and was attempting to add them to the list object after calling node.items instead of just calling add on the node itself. 

Still not sure what that stacktrace is about though...
