### ISSUE TITLE
.trashed has a NoneType error when comparing timestamps

### ISSUE THREAD

**Issue by castaway** [kiwiz/gkeepapi#79]
Using current gkeep (command line client) and latest (from pip) gkeepapi: listing all notes produces this error:
```
  File "/home/pi/gkeep/dev/gkeep/google_keep_tasks/notes.py", line 75, in print_note
    note_id += u' 🗑' if note.deleted or note.trashed else ''
  File "/home/pi/.local/lib/python2.7/site-packages/gkeepapi/node.py", line 1103, in trashed
    return self.timestamps.trashed > NodeTimestamps.int_to_dt(0)
TypeError: can't compare datetime.datetime to NoneType
```

**Comment by kiwiz** [comment]
Should be fixed as of 8a8c4144f9613a1500d67f4c64c3bb6c71e9f92f.

**Comment by castaway** [comment]
Impressively fast, thanks! 1 more question if I may..

Do you have issues with logins just not working? I've been helping a friend who wants to have it print one of their notes (for a shopping list), and his login keeps getting the ```Error] GKeep Exception:
LoginError: Check credentials file. The syntax is: <username> <password>``` error, even when the same set of credentials worked fine the previous day.. 

I can start a new issue if you think its something worth looking at.

**Comment by kiwiz** [comment]
Hmm, that's a new error to me. Can you open a new ticket please?
