### ISSUE TITLE
Missing key for <class 'gkeepapi.node.Note'>

### ISSUE THREAD

**Issue by shapecoder** [kiwiz/gkeepapi#8]
Very nice work on this API. I tried it real quick and I seem to be able to access my notes. However, when syncing I get the following errors:

Missing key for <class 'gkeepapi.node.Note'> key roleInfo
Missing key for <class 'gkeepapi.node.Note'> key realtimeDataServerVersion
Missing key for <class 'gkeepapi.node.Note'> key realtimeModelVersion
Missing key for <class 'gkeepapi.node.Note'> key lastModifierEmail
Missing key for <class 'gkeepapi.node.Note'> key roleInfo
Missing key for <class 'gkeepapi.node.Note'> key realtimeDataServerVersion
Missing key for <class 'gkeepapi.node.Note'> key realtimeModelVersion
Missing key for <class 'gkeepapi.node.Note'> key lastModifierEmail

I'm only running the following code:

```
import gkeepapi

keep = gkeepapi.Keep()
keep.login('[user]', '[password]')

keep.sync()
```

I figured it might be older notes which don't have those attributes or something. So I cleaned a lot of stuff up and made all new notes, still have the same issue.

**Comment by kiwiz** [comment]
Thanks. :]

Looks like this only happens on Python 3 because the default is to log `warnings` to STDERR. Since this warning isn't actionable by users, I've just turned the lines in question to use `info`. I've pushed up 0.9.6 with this change.

**Comment by shapecoder** [comment]
Oh sorry, forgot to mention I was using Python 3 indeed. Just installed 0.9.6 and works like a charm :) thanks!
