### ISSUE TITLE
Intermittent login errors

### ISSUE THREAD

**Issue by castaway** [kiwiz/gkeepapi#80]
GKeep (dev), gkeepapi (latest from pip) we keep having an issue where the same set of credentials / same file even, sometimes works fine, and sometimes says: ```Error] GKeep Exception: LoginError: Check credentials file. The syntax is: <username> <password>```

It was my friends account, not mine.. I initially assumed somehow he'd messed up the credentials file, re-edited it, then it worked.. he took the Pi it was on home, re-ran it, it didn't work.

It occurs to me the credentials *file* is a gkeep cli thing - is there a way to see the error at a lower level?

**Comment by kiwiz** [comment]
GKeep isn't maintained by me, but I took a quick look. It seems that this [line](https://github.com/Nekmo/gkeep/blob/9a67c35fa2f5742bdb9d48733b5e6d93902ef031/google_keep_tasks/management.py#L17) is swallowing the error and raising a generic one. If you remove that `try` `except` block, you'll be able to see the underlying error.

**Comment by kiwiz** [comment]
Gonna close this for now, since this issue is actually for the GKeep project. Feel free to open a new issue if you've any further questions. Stay safe!
