### ISSUE TITLE
Grab the id using .find(querry="title")

### ISSUE THREAD

**Issue by clandestinz** [kiwiz/gkeepapi#82]
How do I get the id of a note using the .find function?I've read the docs but didn't find anything useful

**Comment by wizpig64** [comment]
Look at [the source code for find](https://github.com/kiwiz/gkeepapi/blob/master/gkeepapi/__init__.py#L803) to see what options it has.

Here i'm passing a string into the `query` kwarg, so it will find my note with the `query in node.title` part of the filter.

```
>>> # after logging in...
>>> keep.find(query='My note with exact title')
<generator object Keep.find.<locals>.<genexpr> at 0x7f4708f029e0>
```

Oh right. keep.find() returns a generator, which means you need to iterate through it, or wrap it with `list()`:

```
>>> for note in keep.find(query='My note with exact title'):
...   print(note.id, note.title)
...
1589112212268.532623078 My note with exact title
>>> note.url
'https://keep.google.com/u/0/#LIST/1589112212268.532623078'
```
