### ISSUE TITLE
Blank Notes are created with the Sample Code

### ISSUE THREAD

**Issue by arunk140** [kiwiz/gkeepapi#9]
Code and Output in Screenshot - (No errors in Terminal)
```
keep = gkeepapi.Keep()
keep.login('...', '...')
keep.sync()

note = gkeepapi.createNote('Todo', 'Eat breakfast')
note.pinned = True
note.color = gkeepapi.node.COLOR['RED']

keep.sync()
```
![screen shot 2017-12-11 at 9 57 38 pm](https://user-images.githubusercontent.com/8670239/33841639-569475a0-debe-11e7-9774-507bd5dd619b.png)

**Comment by nimbuscrenel** [comment]
I noticed this too. I was able to set the title successfully outside of the 'createNote' function like this:
`keep = gkeepapi.Keep()
keep.login('...', '...')
keep.sync()

note = keep.createNote()
note.pinned = True
note.title = 'Todo'
note.text = 'Eat breakfast'
note.color = gkeepapi.node.COLOR['RED']


keep.sync()`
However, trying to set any 'text' still doesn't work.

**Comment by kiwiz** [comment]
Wow, nice catch! I've been using gkeepapi to modify just existing notes, so I didn't see this. Should be fix per the commit above (and a new version has been pushed.

**Comment by nimbuscrenel** [comment]
@kiwiz I'm seeing a new error after your commit:
```python
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/gkeepapi/__init__.py", line 455, in sync
    nodes=[i.save() for i in self._findDirtyNodes()],
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/gkeepapi/__init__.py", line 535, in _findDirtyNodes
    for node in self._nodes.values():
  RuntimeError: dictionary changed size during iteration
```

Should I open a separate issue?

**Comment by kiwiz** [comment]
Should be fixed in 0.9.8.

**Comment by nimbuscrenel** [comment]
@kiwiz Yes! Seems to be working great now.

**Comment by arunk140** [comment]
Thanks! @kiwiz Works like a charm now!
