### ISSUE TITLE
gkeepapi.exception.LoginException: (u'NeedsBrowser', u'To access your account, you must sign in on the web. Touch Next to start browser sign-in.')

### ISSUE THREAD

**Issue by s-kaczmarek** [kiwiz/gkeepapi#95]
Hi, 

I was trying to test example provided in readme. When I run this example i get error:

gkeepapi.exception.LoginException: (u'NeedsBrowser', u'To access your account, you must sign in on the web. Touch Next to start browser sign-in.')

I provided valid login credentials in success = keep.login()

**Comment by s-kaczmarek** [comment]
Different error, but resolution is the same as here: https://github.com/kiwiz/gkeepapi/issues/81

**Comment by kiwiz** [comment]
Closing since the issue appears to be resolved.

**Comment by honzasjk** [comment]
> Different error, but resolution is the same as here: #81

Dear s-kaczmarek, please would you tell me how did you particularly solved the issue? I'm having the same problem ('NeedsBrowser', 'To access your account,..)  I tried everything mentioned in the thread but still the same. I'm trying to log in to my university-google account. I turned on 2FA, set up app password, updated Python first to 3.7.7, then to 3.8 still no luck. Then tried with regular password followed the captcha link, still the same. Do you think the problem could be the fact that it is not a "regular" google account? (I'm able to log in to my non-educational private gmail without any problems)

**Comment by s-kaczmarek** [comment]
Hi,

I did just steps described here: https://github.com/kiwiz/gkeepapi/issues/81 and it worked like charm.I'm concerned about this capcha part. It is all supposed to work automatically without any capcha. I think it would be best if you just try on your personal account first.

**Comment by darthwalsh** [comment]
I was having this issue, on Windows Python 3.10.7, even though a couple years ago everything was working. Even though I'd installed `requests==2.23.0` I kept getting the error `gkeepapi.exception.LoginException: ('NeedsBrowser...`.

_**I created a fresh venv and the error went away.**_

Older, broken enviornment:
```
certifi==2020.12.5
chardet==3.0.4
future==0.18.2
gkeepapi==0.13.4
gpsoauth==1.0.0
idna==2.10
pycryptodomex==3.10.1
requests==2.23.0
six==1.16.0
urllib3==1.25.11
```
(So one of the other old deps must also be at fault, maybe `certifi` or  `gpsoauth`.)

New environment where I just installed `gkeepapi` then `requests==2.23.0` gave this working environment:
```
certifi==2022.6.15.1
chardet==3.0.4
charset-normalizer==2.1.1
future==0.18.2
gkeepapi==0.14.2
gpsoauth==1.0.2
idna==2.10
pycryptodomex==3.15.0
requests==2.23.0
urllib3==1.25.11
```

**Comment by guoguo12** [comment]
I was getting the `NeedsBrowser` error on Cygwin. Updating my Cygwin Python version (by [downloading the installer](https://www.cygwin.com/install.html) and upgrading all the packages) fixed it, although now I'm getting the error message in #81.
