### ISSUE TITLE
How to use this API  to grab image text

### ISSUE THREAD

**Issue by ppsingh98** [kiwiz/gkeepapi#96]
Google Keep allows extracting text from image by 'Grab Image Text' option. How can that feature be used through gkeepapi? Thanks.

**Comment by kiwiz** [comment]
Updated `gkeepapi` to `0.13.0`, which exposes this better. I've updated the docs [here](https://gkeepapi.readthedocs.io/en/latest/#media), but here's an example:

```py
n = keep.get('some_note_id')
n.drawings[0].extracted_text
```

**Comment by ppsingh98** [comment]
Thanks a lot for the update. Can we add an image to a note using gkeepapi?

**Comment by kiwiz** [comment]
Unfortunately not. IIRC, this required getting a different kind of authentication token when I last looked.
